// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkiNet.Infrastructure.Data;

#nullable disable

namespace SkiNet.Infrastructure.Data.Migrations
{
  [DbContext(typeof(StoreContext))]
  [Migration("20220901140624_InitialCreate")]
  partial class InitialCreate
  {
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
      modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

      modelBuilder.Entity("SkiNet.Svc.Entities.Product", b =>
      {
        b.Property<int>("Id").ValueGeneratedOnAdd().HasColumnType("INTEGER");
        b.Property<string>("Name").HasColumnType("TEXT");
        b.HasKey("Id");
        b.ToTable("Products");
      });
#pragma warning restore 612, 618
    }
  }
}